app = "mgbric"
primary_region = "ams"

# Enable auto-deployment from GitHub
[deploy]
  strategy = "rolling"
  wait_timeout = "5m"

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_ENV = "production"
  BUILD_TIME = "2026-01-17-00-00"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
